# AIM: WAPP TO CREATE ARRAYS USING DIFFERENT FUNCTIONS OF NUMPY
import numpy as np
# 1. CREATING ARRAYS USING ARANGE FUNCTION
print("1. CREATING ARRAYS USING ARANGE FUNCTION")
arr1 = np.arange(2,21,2)
print(arr1)
print()
# 2. CREATING ARRAYS USING ZEROS FUNCTION
print("2. CREATING ARRAYS USING ZEROS FUNCTION")
arr2 = np.zeros((3,3))
print(arr2)
print()
# 3. CREATING ARRAYS USING ONES FUNCTION
print("3. CREATING ARRAYS USING ONES FUNCTION")
arr3 = np.ones((3,3))
print(arr3)
print()
# 4. CREATING ARRAYS USING EMPTY FUNCTION
print("4. CREATING ARRAYS USING EMPTY FUNCTION")
arr4 = np.empty((3,3))
print(arr4)
print()
# 5. CREATING ARRAYS USING EYE FUNCTION
print("5. CREATING ARRAYS USING EYE FUNCTION")
arr5 = np.eye(3)
print(arr5)
print()
# 6. CREATING ARRAYS USING RANGE FUNCTION
print("6. CREATING ARRAYS USING RANGE FUNCTION")
arr6 = np.arange(1,21)
print(arr6)
print()
# 7. CREATING ARRAYS USING RANDINT FUNCTION
print("7. CREATING ARRAYS USING RANDINT FUNCTION")
arr7 = np.random.randint(1,21,10)
print(arr7)
print()
# 8. CREATING ARRAYS USING RAND FUNCTION
print("8. CREATING ARRAYS USING RAND FUNCTION")
arr8 = np.random.rand(3,3)
print(arr8)
print()
# 9. CREATING ARRAYS USING RANDN FUNCTION
print("9. CREATING ARRAYS USING RANDN FUNCTION")
arr9 = np.random.randn(3,3)
print(arr9)
print()
# 10. CREATING ARRAYS USING RAND FUNCTION
print("10. CREATING ARRAYS USING RAND FUNCTION")
arr10 = np.random.random((3,3))
print(arr10)
print()
# 11. CREATING ARRAYS USING ARANGE FUNCTION
print("11. CREATING ARRAYS USING ARANGE FUNCTION")
arr11 = np.arange(1,21,2)
print(arr11)
print()
